export const PROGRAMS = [
  { code: "BACOM",  title: "Bachelor of Arts in Communication", short: "Communication",       dept: "College of Arts & Sciences",  img: `${BASE}/program_logo/bacom.jpg`,
    desc: "Develops skilled communicators across media, journalism, public relations, and organizational contexts.", year: "4-Year Program", featured: false },
  { code: "BSIS",   title: "BS Information Systems",            short: "Information Systems", dept: "College of Computing",        img: `${BASE}/program_logo/bsis.png`,
    desc: "Bridges technology and organizational decision-making. Students learn systems analysis, database management, and enterprise software — preparing them for roles in IT management and consulting.", year: "4-Year Program", featured: true },
  { code: "BSMATH", title: "BS Mathematics",                   short: "Mathematics",         dept: "College of Arts & Sciences",  img: `${BASE}/program_logo/bsmath.jpg`,
    desc: "Trains analytical thinkers in pure and applied mathematics for careers in research, finance, and data science.", year: "4-Year Program", featured: false },
  { code: "BSN",    title: "BS Nursing",                       short: "Nursing",             dept: "College of Health Sciences",   img: `${BASE}/program_logo/bsn.jpg`,
    desc: "Prepares compassionate nurses for local and international practice, grounded in evidence-based care and clinical training.", year: "4-Year Program", featured: false },
  { code: "BPED",   title: "Bachelor of Physical Education",   short: "Physical Education",  dept: "College of Education",        img: `${BASE}/program_logo/bped.jpg`,
    desc: "Produces qualified PE teachers and coaches grounded in kinesiology, health promotion, and youth development.", year: "4-Year Program", featured: false },
  { code: "BPAD",   title: "Bachelor of Public Administration",short: "Public Administration", dept: "College of Governance",       img: `${BASE}/program_logo/bpad.jpg`,
    desc: "Develops public servants and policy analysts committed to ethical governance and community development.", year: "4-Year Program", featured: false },
  { code: "BSC",    title: "BS Criminology",                   short: "Criminology",         dept: "College of Criminal Justice", img: `${BASE}/bscrim.jpeg`,
    desc: "Equips graduates for law enforcement, forensics, and criminal justice with rigorous academic and practical foundations.", year: "4-Year Program", featured: false },
  { code: "ECE",    title: "Early Childhood Education",        short: "Early Childhood Ed.", dept: "College of Education",        img: `${BASE}/bece.jpeg`,
    desc: "Trains educators in developmentally appropriate practices for children from birth through age eight.", year: "4-Year Program", featured: false },
  { code: "SNE",    title: "Special Needs Education",          short: "Special Needs Ed.",   dept: "College of Education",        img: `${BASE}/bsne.jpeg`,
    desc: "Prepares inclusive educators with specialized strategies to support learners with diverse abilities and needs.", year: "4-Year Program", featured: false },
];
